on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '21.0.1'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.13.8'
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build apk --no-tree-shake-icons
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
            host: smtp.google.com
            port: 465
            account: ${{secrets.ACCOUNT}}
            password: ${{secrets.MAIL_PASSWORD}}
            sender: YasserHassan
            from: ${{secrets.MAIL_ADDRESS}}
            to: yasserhassan.it.95@gmail.com
            subject: Posts app Release.
            body: new build released.
            # Optional content type (defaults to text/plain)
            contentType: text/plain
            # Optional attachment files (JSON type. require property 'path')
            attachments: '[{"path":"README.md"}]'





# push to master
# pull from master